# Generated by Django 4.2 on 2023-04-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoGenerations", "0002_useraccount_delete_todo"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="name",),
        migrations.AddField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
